[package]
name = "aoc2015"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc = { version = "0.1.0", path = "../aoc" }
itertools = "0.14.0"
md5 = "0.7.0"
utils = { version = "0.1.0", path = "../utils" }
